[log]
file="./log.xml"
level="trace"

[dns]
type="default"
server="cloudflare-dns.com"
addr="1.1.1.1:853"
local_resolve=true

[server]
port=80
pretend="https://www.kernel.org"
timeout=15
secure=false
cert_file=""
key_file=""

[db]
type="sqlite3"
username="root"
password="password"
host="localhost"
port=1433
database="relaybaton.db"
